steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir tmp
      (docker pull gcr.io/$PROJECT_ID/meteor-app-builder:${TAG_NAME}${BRANCH_NAME} && echo "${TAG_NAME}${BRANCH_NAME}" > tmp/base) ||
        echo "master" > tmp/base

      docker pull "gcr.io/$PROJECT_ID/meteor-app-builder:$(cat tmp/base)" || true

      docker build \
          --cache-from "gcr.io/$PROJECT_ID/meteor-app-builder:$(cat tmp/base)" \
          -t gcr.io/$PROJECT_ID/meteor-app-builder:${TAG_NAME}${BRANCH_NAME} \
          -t gcr.io/$PROJECT_ID/meteor-app-builder:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/meteor-app-builder:latest \
          --target builder \
          .

      docker build \
          --cache-from "gcr.io/$PROJECT_ID/meteor-app-builder:$SHORT_SHA" \
          -t gcr.io/$PROJECT_ID/meteor-app:${TAG_NAME}${BRANCH_NAME} \
          -t gcr.io/$PROJECT_ID/meteor-app:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/meteor-app:latest \
          .
timeout: 1200s
images: [
  'gcr.io/$PROJECT_ID/meteor-app-builder:$SHORT_SHA',
  'gcr.io/$PROJECT_ID/meteor-app-builder:${TAG_NAME}${BRANCH_NAME}',
  'gcr.io/$PROJECT_ID/meteor-app-builder:latest',
  'gcr.io/$PROJECT_ID/meteor-app:$SHORT_SHA',
  'gcr.io/$PROJECT_ID/meteor-app:${TAG_NAME}${BRANCH_NAME}',
  'gcr.io/$PROJECT_ID/meteor-app:latest'
]
